App: V1.1.o funkcijos.o
	g++ V1.1.o funkcijos.o -o3 App

V1.1.o: V1.1.cpp funkcijos.h
	g++ -c ND2_v1.0.cpp funkcijos.h

func.o: funkcijos.cpp funkcijos.h struktura.h
	g++ -c funkcijos.cpp funkcijos.h struktura.h

clean: rm *.o *.gch App
